# Generated by Django 3.2.7 on 2021-11-08 13:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None),
        ),
        migrations.CreateModel(
            name='FakeUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='URL')),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.banks', verbose_name='Относится к банку')),
            ],
            options={
                'verbose_name': 'Фейковый url',
                'verbose_name_plural': 'Фейковые url',
            },
        ),
    ]
